[platformio]
build_dir = C:/pio-aq/build
libdeps_dir = C:/pio-aq/libdeps

[env:m5stack-cores3-lite]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_qspi
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DLV_CONF_PATH="${PROJECT_DIR}/include/lv_conf.h"
lib_deps =
    m5stack/M5Unified @ ^0.2.11
    m5stack/M5GFX @ ^0.2.11
    lvgl/lvgl @ ^8.3.11
    sensirion/Sensirion I2C SEN66 @ ^1.2.0
    bblanchon/ArduinoJson @ ^7.0.4
    knolleary/PubSubClient @ ^2.8
    xreef/SimpleFTPServer @ ^3.0.1
    espressif/esp32-camera @ ^2.0.4
